const container=document.querySelector("#projects-container");let projects=[{img:"images/proyecto-1.webp",title:"CRM - administrador de clientes",description:"Este proyecto de CRM permite gestionar clientes mediante una interfaz web, donde se pueden crear, editar y eliminar registros.",link:"https://crmadminclients.netlify.app/",github:"https://github.com/001-ANGEL/CRM---Administador-de-Clients"},{img:"images/proyecto-3.webp",title:"Buscador de Recetas",description:"Buscador de recetas permite a los usuarios encontrar recetas de cocina fácilmente.",link:"https://buscador-de-recetas-1.netlify.app/",github:"https://github.com/001-ANGEL/Buscador-de-Recetas"},{img:"images/proyecto-4.webp",title:"Cotizador de Criptomonedas",description:"Cotizador de criptomonedas permite a los usuarios consultar el valor actualizado de diferentes criptomonedas en tiempo real.",link:"https://cotizador-de-criptomonedas1.netlify.app/",github:"https://github.com/001-ANGEL/Cotizador-de-Criptomonedas"},{img:"images/proyecto-2.webp",title:"Agencia de Viajes",description:"Desarrollé el backend para una agencia de viajes que permite a los usuarios explorar los detalles de cada viaje.",link:"https://github.com/001-ANGEL/Agencias-de-Viajes-con-Node.js",github:"https://github.com/001-ANGEL/Agencias-de-Viajes-con-Node.js"}];projects.forEach(project=>{const projectBox=document.createElement("DIV");projectBox.classList.add("project");projectBox.classList.add("project");projectBox.setAttribute("data-aos","zoom-in-up");projectBox.innerHTML=`
  <div class="project-img">
  <img src="${project.img}" alt="proyecto de ${project.title}">
  </div>
  
  <div class="project-title">
      <h3>${project.title}</h3>
  </div>

  <div class="project-description">
      <p>${project.description}</p>
  </div>
  
   <div class="project-button">
   <a href="${project.link}" target="_blank">Ver Proyecto</a>
   <a href="${project.github}" target="_blank" class="github-icon"><svg xmlns="http://www.w3.org/2000/svg" x-bind:width="size" x-bind:height="size" viewBox="0 0 24 24" fill="none" stroke="currentColor" x-bind:stroke-width="stroke" stroke-linecap="round" stroke-linejoin="round" width="24" height="24" stroke-width="2">
<path d="M9 19c-4.3 1.4 -4.3 -2.5 -6 -3m12 5v-3.5c0 -1 .1 -1.4 -.5 -2c2.8 -.3 5.5 -1.4 5.5 -6a4.6 4.6 0 0 0 -1.3 -3.2a4.2 4.2 0 0 0 -.1 -3.2s-1.1 -.3 -3.5 1.3a12.3 12.3 0 0 0 -6.2 0c-2.4 -1.6 -3.5 -1.3 -3.5 -1.3a4.2 4.2 0 0 0 -.1 3.2a4.6 4.6 0 0 0 -1.3 3.2c0 4.6 2.7 5.7 5.5 6c-.6 .6 -.6 1.2 -.5 2v3.5"></path>
</svg></a>
 </div>

 
`;container.appendChild(projectBox)});const nav=document.querySelector("#navVisible");const btnOpen=document.querySelector("#btnOpen");const btnClose=document.querySelector("#btnClose");const sections=[document.querySelector("#hero"),document.querySelector("#aboutMe"),document.querySelector("#experience"),document.querySelector("#projects"),document.querySelector("#skills"),document.querySelector("#contact")];btnOpen.addEventListener("click",()=>{nav.classList.add("ul-visible")});btnClose.addEventListener("click",()=>{nav.classList.remove("ul-visible")});const anchors=nav.querySelectorAll("a");sections.forEach(section=>{section.addEventListener("click",()=>{nav.classList.remove("ul-visible")})});anchors.forEach(anchor=>{anchor.addEventListener("click",()=>{nav.classList.remove("ul-visible")})});const navLinks=document.querySelectorAll("nav ul li a");const section=document.querySelectorAll("section");function updateActiveLink(){let index=section.length;while(--index&&window.scrollY+50<section[index].offsetTop){}navLinks.forEach(link=>link.classList.remove("active"));navLinks[index].classList.add("active")}window.addEventListener("scroll",updateActiveLink);window.addEventListener("load",updateActiveLink);AOS.init({duration:700,once:true});const btn=document.getElementById("button");const userName=document.querySelector("#from_name");const message=document.querySelector("#message");const emailID=document.querySelector("#emai_id");const form=document.querySelector("#form");form.addEventListener("submit",event=>{event.preventDefault();if(userName.value===""||message.value===""||emailID.value===""){showAlert("Todos los campos son obligatorios")}else{if(!validateEmail(emailID.value)){showAlert("Ingrese un Email válido")}else{btn.value="Enviando...";const serviceID="default_service";const templateID="template_ycfp17d";emailjs.sendForm(serviceID,templateID,form).then(()=>{btn.value="Enviar Email";Swal.fire({position:"top-end",icon:"success",title:"Enviado Correctamente!",showConfirmButton:false,timer:1e3});setTimeout(()=>{location.href="#hero";setTimeout(()=>{location.reload()},1e3)},2e3)},err=>{btn.value="Enviar Email";Swal.fire({position:"top-end",icon:"error",title:"Enviado Correctamente!",showConfirmButton:false,timer:1e3});console.log(err)})}}});function showAlert(message){const existsAlert=document.querySelector(".alert-p");if(!existsAlert){const field=document.querySelector(".field-alert");const alert=document.createElement("P");alert.classList.add("alert-p");alert.textContent=message;field.appendChild(alert);setTimeout(()=>{alert.remove()},3e3)}}function validateEmail(emailID){const regex=/^\w+([.-_+]?\w+)*@\w+([.-]?\w+)*(\.\w{2,10})+$/;return regex.test(emailID)}